on:
  push:
    branches:
      - main

jobs:
  installation_and_deployment:
    runs-on: ubuntu-latest
    permissions:
      id-token: 'write'
    steps:
      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      
      - name: Checkout repo
        uses: actions/checkout@v4
      
      - uses: hashicorp/setup-terraform@v3
        with:
         terraform_version: latest
      
      - name: path
        run: echo "$GITHUB_WORKSPACE"

      - name: Terraform Init
        id: init
        run: terraform init
        working-directory: ./dev

      - name: Terraform plan
        id: plan
        env:
         ADMIN_USERNAME: ${{ secrets.ADMIN_USERNAME }}
         ADMIN_PASSWORD: ${{ secrets.ADMIN_PASSWORD }}
        run: terraform plan -var "admin_username=${{ secrets.ADMIN_USERNAME }}" -var "admin_password=${{ secrets.ADMIN_PASSWORD }}"
        working-directory: ./dev


  manual-approval:
    needs: installation_and_deployment
    runs-on: ubuntu-latest
    environment: Manual-approval  # 👈 This triggers the manual review step
    steps:
      - name: Approval Passed
        run: echo "Manual approval completed!"
      
      - name: Check directory contents before apply
        run: ls -R $GITHUB_WORKSPACE
        working-directory: ./dev
    
      - name: Terraform apply
        id: apply
        if: github.ref == 'refs/heads/main'
        env:
         ADMIN_USERNAME: ${{ secrets.ADMIN_USERNAME }}
         ADMIN_PASSWORD: ${{ secrets.ADMIN_PASSWORD }}
        run: terraform apply -auto-approve -var "admin_username=${{ secrets.ADMIN_USERNAME }}" -var "admin_password=${{ secrets.ADMIN_PASSWORD }}"
        working-directory: ./dev
