on:
  push:
    branches:
      - main

jobs:
  installation_and_deployment:
    runs-on: ubuntu-latest
    permissions:
      id-token: 'write'
    steps:
      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      
      - name: Checkout repo
        uses: actions/checkout@v4
      
      - uses: hashicorp/setup-terraform@v3
        with:
         terraform_version: latest
      
      - name: path
        run: echo "$GITHUB_WORKSPACE"

      - name: Terraform Init
        id: init
        run: terraform init
        working-directory: ./dev

      - name: Terraform plan
        id: plan
        run: terraform plan
        working-directory: ./dev
      
      # - name: Terraform apply
      #   id: apply
      #   run: terraform apply -auto-approve
      #   working-directory: ./dev